apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: users-svc-deployment
spec:
  selector:
    matchLabels:
      app: users
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: usersservice
        image: usersservice:1.0
        ports:
        - containerPort: 8080